# fly.toml app configuration file generated for image-server-ancient-sky-7642 on 2024-08-23T17:04:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'image-server-ancient-sky-7642'
primary_region = 'lhr'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'image-server-ancient-sky-7642.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
